### ISSUE TITLE
Run UCD container with host networking

### ISSUE THREAD

**Issue by sudhakarau1** [stackinabox/vagrant-opdk-box#3]
I had to run the UCD container with --net-host (docker run --net=host -d --restart=always --name=urbancode_deploy -e LICENSE=accept stackinabox/urbancode-deploy:6.2.1.1.78164) , otherwise the Openstack instances couldn't get to the UCD container. 
--net=host for UCD also means the Designer container can't use --link to it

**Comment by tpouyer** [comment]
Done
