### ISSUE TITLE
unable to launch instance on 0.9.6

### ISSUE THREAD

**Issue by sudhakarau1** [stackinabox/vagrant-opdk-box#7]
The ubuntu 14.04/16.04 images threw an error:
Message:
    Exceeded maximum number of retries. Exceeded max scheduling attempts 3 for instance c3f4086e-c882-4ba3-9689-691b40d95bbf. Last exception: Invalid raw.lxc line: | 
Code :   500
Details :     File "/opt/stack/nova/nova/conductor/manager.py", line 492, in build_instances filter_properties, instances[0].uuid) File "/opt/stack/nova/nova/scheduler/utils.py", line 184, in populate_retry raise exception.MaxRetriesExceeded(reason=msg)

**Comment by tpouyer** [comment]
I've stopped working on this repo, please see the latest release of stackinabox.io for similar capabilities.
